### ISSUE TITLE
Decayed Horrors

### ISSUE THREAD

**Issue by EvilHogg** [OfficialNeocron/public-bug-tracker#10]
I don't really know how to describe this. Black magic f'ery. I believe this is well known.

![decayed-horror-absorber](https://user-images.githubusercontent.com/34963912/231479496-143bffd7-0e5b-4606-b521-648674e3e0bb.png)

**Comment by Xanthos-NST** [comment]
Decyed H. can self-casts shields, is that what you mean?

**Comment by EvilHogg** [comment]
Correct. The self cast shield, the yellow damage (I believe is an issue?), and when you are damaging it, its health doesn't go down for some time. These may or may not all be related, but that's what I see.

**Comment by Virtus-NST** [comment]
I am applying a test fix to this currently and plan to test if it's worked.

**Comment by Virtus-NST** [comment]
I've tested this and found none of the ones I killed ever had an absorber. I'm happy this is fixed and will hit Titan with the next update.

**Comment by EvilHogg** [comment]
Awesome, may I ask what the issue was?
