### ISSUE TITLE
Loot Does Not Stack

### ISSUE THREAD

**Issue by EvilHogg** [OfficialNeocron/public-bug-tracker#16]
Advanced Navigation System V2.03 does not stack. This is dropped from hoverbots/hoverbombers.

![nans2 03-nostack](https://user-images.githubusercontent.com/34963912/233837064-154b95d5-cc31-479f-bea2-10c73de1a709.jpg)

**Comment by Xanthos-NST** [comment]
Will be fixed with the next Titan Release.
It will probably only affect new drops.
