### ISSUE TITLE
Glider and Jelly Carcass Names

### ISSUE THREAD

**Issue by EvilHogg** [OfficialNeocron/public-bug-tracker#18]
The names of the glider and jelly carcasses/trophies no longer match the names of the mobs that drop them. For example, the floating jelly carcass is dropped by the swamp slime worm. Note that dialog for master hunter trophies may need to be updated if these names are changed. Mutant bat and cockroach could use the same review as well.

**Comment by Virtus-NST** [comment]
Gliders are named correctly already. Jelly is dropped by "FIERCE FLOATING JELLY"& "Swamp Slimeworm". Will address this.

**Comment by Virtus-NST** [comment]
Change fixed in next patch.
