### ISSUE TITLE
Warbot Carcasses Wrong Color

### ISSUE THREAD

**Issue by EvilHogg** [OfficialNeocron/public-bug-tracker#2]
The new warbots drop the wrong color carcass. For example, the gold warbot drops the black carcass, and the black warbot drops the gold carcass. This was previously reported in discord, and I have not found any carcasses since then. So I am not sure if its been fixed.

![web-wrong-color](https://user-images.githubusercontent.com/34963912/231475642-c17a139f-eddc-4d5b-9a97-5230d19bc48a.png)

**Comment by Virtus-NST** [comment]
I've committed a change to fix these two warbots dropping the wrong remains, will be shipped to Titan soon - Please test, though :

**Comment by EvilHogg** [comment]
I am not sure how to test this in a short period of time.
