### ISSUE TITLE
Lack of Legacy Warbots/Titans

### ISSUE THREAD

**Issue by tobgen** [OfficialNeocron/public-bug-tracker#20]
The lack of Legacy Warbot/Titan makes missions very hard.

**Comment by Virtus-NST** [comment]
I've added to my list. The below discord message has a little context.


> Warbot spawns are heavily weighted to 1 type and the others only have a zone or 2 each. I'd like to equal it out a bit more and have,  for example yellow in the desert, blue in steppe, red in NW corner. That way you can always find the ones you need and have some zone variety for each

https://discord.com/channels/244237952199163907/704583252656259101/1099363135783190718

**Comment by Xanthos-NST** [comment]
Changed on PTS.
