### ISSUE TITLE
GR Bug

### ISSUE THREAD

**Issue by EvilHogg** [OfficialNeocron/public-bug-tracker#24]
If you are in a zone when the clock resets to 00:00 and you try to GR out of that zone, you get SI and do not warp anywhere.

**Comment by EvilHogg** [comment]
I may be incorrect on when/how this bug happens and cannot provide more insight at this time.

**Comment by Xanthos-NST** [comment]
Have you used a double click on the target or used the warp button, when this occured?

**Comment by EvilHogg** [comment]
Last time this happened it was just after a zone reset. I double clicked on the target.

**Comment by Xanthos-NST** [comment]
Closed - internally fixed.
