### ISSUE TITLE
Profession Descriptions Do Not Scroll

### ISSUE THREAD

**Issue by EvilHogg** [OfficialNeocron/public-bug-tracker#27]
Some or all of the Profession descriptions that are part of the character creation process do not scroll.

![image](https://github.com/OfficialNeocron/public-bug-tracker/assets/34963912/a9bf6dae-6de5-4cb5-bae8-e520666e5464)

**Comment by Xanthos-NST** [comment]
What resolution are you playing with?

**Comment by EvilHogg** [comment]
Borderless fullscreen 1920x1080

**Comment by Xanthos-NST** [comment]
Should be fixed with .577
