### ISSUE TITLE
Construction Status Bar Number

### ISSUE THREAD

**Issue by EvilHogg** [OfficialNeocron/public-bug-tracker#32]
Occasionally when you research something, the construction icon will appear in the bottom right with a large number. Sometimes the number will appear for a faction of a second and disappear throughout the research process.

![image](https://github.com/OfficialNeocron/public-bug-tracker/assets/34963912/3c18c08e-6782-48d9-89e7-6c29b644c268)

**Comment by Xanthos-NST** [comment]
Fixed on PTS.
