### ISSUE TITLE
Venture Warp Text Cut Off

### ISSUE THREAD

**Issue by EvilHogg** [OfficialNeocron/public-bug-tracker#36]
The venture warp menu text is cut off. You are able to scroll it if you grab the right side of the window, but no scroll bar is visible. Suggest simply removing a couple words to prevent the need to scroll, such as "system"

![venture_warp_window_scroll](https://github.com/OfficialNeocron/public-bug-tracker/assets/34963912/5d6a0966-7697-4bcf-b615-1e9403235093)

**Comment by theRogueGnisha** [comment]
Fixed on PTS.
-G
