### ISSUE TITLE
Master Hunter Dialog at Trade-In

### ISSUE THREAD

**Issue by EvilHogg** [OfficialNeocron/public-bug-tracker#38]
When you trade-in the parts for trophy number one the NPC states the following, yet you still receive the trophy:

![image](https://github.com/OfficialNeocron/public-bug-tracker/assets/34963912/95d967b7-ece6-4dd9-bde4-63f131128acd)

![image](https://github.com/OfficialNeocron/public-bug-tracker/assets/34963912/05c55a73-ef8b-4b4b-9a60-31e4b47c206d)

Note this may also happen for the other trophies. I did not have the other parts.

**Comment by EvilHogg** [comment]
I am requesting that someone verify this first. I no longer have the parts.

**Comment by Xanthos-NST** [comment]
Fixed, will be shipped with the next Titan Update.
