### ISSUE TITLE
TSU FMS Pic Items Wrong Color

### ISSUE THREAD

**Issue by EvilHogg** [OfficialNeocron/public-bug-tracker#4]
The orange pictures are the wrong color. This was previously reported in discord.

![tt-fsm-metal-orange-wrong-color](https://user-images.githubusercontent.com/34963912/231476278-64c131d4-0507-4df4-a3ed-7df7e1a33e8b.png)

**Comment by Virtus-NST** [comment]
I've committed a change to fix this orange icon, will be shipped to Titan soon - Please test, though :)

**Comment by EvilHogg** [comment]
Metal orange is still yellow. All other oranges are correct. I also just noticed that metal red is actually orange....sorry, it's very subtle.
