### ISSUE TITLE
Items in Belt Sell to Vendor first not Inventory

### ISSUE THREAD

**Issue by Eldrich81** [OfficialNeocron/public-bug-tracker#42]
I got a Granades Bug this is One left not Useable, so i try to Sell it back to Vendor. I Click 3-4 Times then i see my Grenades in belt got Sell. That Bug Work with all Items Like Flashlight, Staminabooster Medis ... [Update to the Bug - Drones are not affectet and dont Sold from Belt. Hope you can work with it]

![grafik](https://github.com/OfficialNeocron/public-bug-tracker/assets/142042851/e4d7229f-8653-4256-8ab1-154d5697a88d)
![grafik](https://github.com/OfficialNeocron/public-bug-tracker/assets/142042851/d13246bc-86b2-4582-b02e-f2f79d2f1fe0)

**Comment by Xanthos-NST** [comment]
Internally fixed.
