### ISSUE TITLE
Ceres Hovertec 'Vulcan' Repair

### ISSUE THREAD

**Issue by EvilHogg** [OfficialNeocron/public-bug-tracker#45]
The Ceres Hovertec does not show the proper repair values. When it has taken small/medium amounts of damage, the repair value is 0. At some point it jumps to a large and incorrect amount.

Hovertec with ~50% damage:
![image](https://github.com/OfficialNeocron/public-bug-tracker/assets/34963912/279f0ed0-85c3-4552-9bf7-6784e5e04040)

Hovertec with 98% damage:
![image](https://github.com/OfficialNeocron/public-bug-tracker/assets/34963912/834b6b20-c01e-4a5e-8672-5860ce28761b)

Repair Cost:
![image](https://github.com/OfficialNeocron/public-bug-tracker/assets/34963912/94a189bf-4f7c-4499-b507-e5752d1c5599)

**Comment by Xanthos-NST** [comment]
Fixed on PTS.
