### ISSUE TITLE
Mixed German and English dialogs on Ore Extractors (Regant Mission)

### ISSUE THREAD

**Issue by tobgen** [OfficialNeocron/public-bug-tracker#46]
Ore Extractor #2 and #4 seems to be a bit confused and have some dialogs in German.
See attached screenshot:
![image](https://github.com/OfficialNeocron/public-bug-tracker/assets/996361/46cb88b7-5a43-4688-994c-3b07d754b45e)

**Comment by Xanthos-NST** [comment]
Fixed on PTS.

-X.
