### ISSUE TITLE
Weapon GFXs lingering for a long time

### ISSUE THREAD

**Issue by Virtus-NST** [OfficialNeocron/public-bug-tracker#49]
Weapon shot FX _(possibly other FXs too)_ are visible for a longer period of time then previously observed. For instance the flamer smoke lingers for a long time and therefore blocks vision.

I have also noticed the same on the RoG / RoLH FXs also.

This may be since the increased framerate patch?

**Comment by theRogueGnisha** [comment]
Fixed on PTS
