### ISSUE TITLE
Warbots don't show correctly from distance

### ISSUE THREAD

**Issue by Virtus-NST** [OfficialNeocron/public-bug-tracker#50]
Warbots with the new models show as a slim shadow from distance and once you get close enough their true model pops in and they look normal.

This effects both Warbots & Titan variants. 

Images attached from "far" & "near"

![image](https://github.com/OfficialNeocron/public-bug-tracker/assets/130667327/dc4a575d-dfac-4ba7-9473-f1fbb3c48b41)
![image](https://github.com/OfficialNeocron/public-bug-tracker/assets/130667327/383e908a-f2fe-43b5-847b-8456cc34572b)

**Comment by Xanthos-NST** [comment]
Fixed on PTS.
