### ISSUE TITLE
PP1 Incorrect Zone Prompt

### ISSUE THREAD

**Issue by EvilHogg** [OfficialNeocron/public-bug-tracker#51]
Of you approach the bum across from Neofrag in PP1 you get the following prompt about entering a sewer zone. 

![image](https://github.com/OfficialNeocron/public-bug-tracker/assets/34963912/038e4151-af84-4525-9833-ff836838fcee)

**Comment by EvilHogg** [comment]
What information do you need?

**Comment by Xanthos-NST** [comment]
Sorry, was a note for me to inspect the map again, if the zone line is too big or w/e.

**Comment by Xanthos-NST** [comment]
Issue found, will be fixed with one of the next updates.
