### ISSUE TITLE
Weapons Missing Labels

### ISSUE THREAD

**Issue by EvilHogg** [OfficialNeocron/public-bug-tracker#52]
Most rare weapons are missing the icon descriptors . For example, a cursed soul would say "CS" over the weapon icon. Here is an example list of the weapons I have access to. 

Note I am *assuming* rare weapons should have their descriptors., but its currently inconsistent in game and most rare items are missing them.

Rifle:

Pain Easer
Dreadfire
Silent Hunter
Ray of God
Terminator
Desperado
First Love
Redeemer
Second Love
Thunderstorm
Libra

Heavy:

Doombeamer
Devourer
Summer Leech
Malediction
Creed
Winding Argument
Ionic Shotgun Cannon
Moonstriker
Warhammer

Pistol:

Ray of Last Hope
Craftsman Dream
Liberator
Wyatt Earp
Judge
Executioner
Sucker Punch
Steiner

Mele and PSI:

Basically all weapons

**Comment by Xanthos-NST** [comment]
Most should be done.
On PTS.

-X
