### ISSUE TITLE
Tech Haven Standard  Cupboard

### ISSUE THREAD

**Issue by EvilHogg** [OfficialNeocron/public-bug-tracker#57]
The latest patch turned the Tech Haven Standard Cupboard into a double stack green cabinet, where as before it was a single blue cabinet.

![image](https://github.com/OfficialNeocron/public-bug-tracker/assets/34963912/e7e2c579-b31a-4e19-92f1-c1ac37a522f5)

![image](https://github.com/OfficialNeocron/public-bug-tracker/assets/34963912/54177efa-8d6c-4340-8d54-3bb6bb373052)

**Comment by Xanthos-NST** [comment]
Fixed on PTS, will be shipped to Titan soon.
