### ISSUE TITLE
Avenger Mine Floating Buildings

### ISSUE THREAD

**Issue by EvilHogg** [OfficialNeocron/public-bug-tracker#6]
Multiple buildings in Avenger Mine are floating.

![avenger_ming_floating_bld](https://user-images.githubusercontent.com/34963912/231477106-363e62e2-5d2a-4ee6-a9f8-5a528cf507c5.jpg)

**Comment by Xanthos-NST** [comment]
"fixed" on PTS, will be shipped soon.
