### ISSUE TITLE
Last dialogue in City Administration Epic mission #6 aborts and 'deletes' quest item

### ISSUE THREAD

**Issue by Harzknopf** [OfficialNeocron/public-bug-tracker#60]
It occurs that the last dialogue with Officer Jenna of the 6th CA mission aborts and the quest item ('broken ethic chip' or similar) disappears. The quest cannot be finished without that item so the quest has to be repeated over and over again until the dialogue does not aborts.

**Comment by Xanthos-NST** [comment]
Fixed on PTS by Gnisha.
