### ISSUE TITLE
FA Research Gloves still wrong after patch

### ISSUE THREAD

**Issue by Haggis3037** [OfficialNeocron/public-bug-tracker#67]
After Patch 577 Research Gloves BPs from TH/FA Database still need Protopharma License for Research Glove (Fetched 1 BP yesterday and 1 about 5 mins ago) and Recycle Glove still needs BD License (checked existing BP).

**Comment by Xanthos-NST** [comment]
Should be fixed now (really) - I've created a new glove entry for the second faction, so both factions have their unique recipe.

I still feel very unhappy with that solution, it may get re-worked at some point.
